### ISSUE TITLE
Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by /sbin/peervpn)

### ISSUE THREAD

**Issue by jazzdd86** [mjuenema/docker-alpine-peervpn#4]
It seems libcrypto1.0 is missing. Please add this to the Dockerfile in your apk add section.
Thanks

**Comment by mjuenema** [comment]
Yes, I can reproduce the problem. I'll attend to it.

**Comment by mjuenema** [comment]
The Docker container needed the following additional packages installed:
* `zlib`
* `zlib-dev`
* `libressl`
* `libressl-dev`

Successfully tested on [Travis-CI](https://travis-ci.org/mjuenema/docker-alpine-peervpn/builds/237388426) and merged into [develop](https://github.com/mjuenema/docker-alpine-peervpn/tree/develop) branch on Github ready for release 0.2.

Currently I don't test an actual VPN connection between Docker containers on Travis-CI so please let me know if you run into any problems.

Regards

Markus
